# Generated by Django 5.1 on 2024-10-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='HobbyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hours', models.PositiveIntegerField()),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobby')),
            ],
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
